
--CREACION DE MI BASE DE DATOS

CREATE DATABASE BD_RELOJ_C


--USAMOS NUESTRA BASE DE DATOS CREADA PARA EMPEZAR A UZAR LAS TABLAS

USE DB_RELOJ_C

--TE TABLA EMPLEADO 

--CREACION DE MIS TABLAS 
CREATE TABLE EMPLEADO
(
ID_EMPLEADO_TE INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE NVARCHAR (50),
APELLIDO_PATERNO NVARCHAR(50),
APELLIDO_MATERNO NVARCHAR(50),
EDAD INT,
SEXO VARCHAR(1),
PUESTO VARCHAR(5), 
CONSTRAINT FK_EMPLEADO_PUESTO FOREIGN KEY (PUESTO) REFERENCES PUESTO(ID_PUESTO)
)
--TC TABLA CHECADA
CREATE TABLE CHECADA
(
ID_EMPLEADO_TC INT,
HORA NVARCHAR (50),
FECHA NVARCHAR (50),
CONSTRAINT FK_CHECADA_EMPLEADO FOREIGN KEY (ID_EMPLEADO_TC) REFERENCES EMPLEADO(ID_EMPLEADO_TE)
)

CREATE TABLE CHECADABONO
(
ID_EMPLEADO_TB INT,
FECHA NVARCHAR (50),
BONO INT,
CONSTRAINT FK_CHECADABONO_EMPLEADO FOREIGN KEY (ID_EMPLEADO_TB) REFERENCES EMPLEADO(ID_EMPLEADO_TE)
)


CREATE TABLE PUESTO
(
ID_PUESTO VARCHAR(5) PRIMARY KEY,
NOMBRE_PUESTO NVARCHAR(50)
)

--INSERTANDO VALORES A PUESTO

INSERT INTO PUESTO VALUES
('DEV','DESARROLLADOR'),
('QA','CONTROL DE CALIDAD'),
('DBA','ADMINISTRADOR DE BASE DE DATOS'),
('SE','INGENIERO DE SOFTWARE'),
('SA','ARQUITECTO DE SOFTWARE'),
('PM','GERENTE DE PROYECTO'),
('CTO','DIRECTOR DE TECNOLOGIA');

--VALORES DE PRUEBA

INSERT INTO EMPLEADO VALUES ('Rivaldo','Mendez','Carranza',25,'M','SE');
INSERT INTO EMPLEADO VALUES ('Manuel','Solis','Perez',20,'M','DBA');
INSERT INTO CHECADA VALUES ('1','18:00','2024-11-03')
INSERT INTO CHECADA VALUES ('1','01:00','2024-11-03')
INSERT INTO CHECADA VALUES ('1','7:00','2024-11-02')
INSERT INTO CHECADA VALUES ('2','6:30','2024-11-02')


SELECT * FROM EMPLEADO;
SELECT * FROM CHECADA;
SELECT * FROM PUESTO;

--CONSULTA QUE ME MUESTRE REGISTRO DE CHECADAS TODAS LAS CHECADAS DE UN EMPLEADO 

SELECT * 
FROM EMPLEADO
JOIN 
CHECADA 
ON EMPLEADO.ID_EMPLEADO_TE = CHECADA.ID_EMPLEADO_TC
WHERE ID_EMPLEADO_TC = 1 AND FECHA = '2024-11-03'

--CONSULTA CON UNA FECHA ESPECIFICA 

SELECT * 
FROM EMPLEADO
JOIN 
CHECADA 
ON EMPLEADO.ID_EMPLEADO_TE = CHECADA.ID_EMPLEADO_TC
WHERE ID_EMPLEADO_TC = 1 AND FECHA = '2024-11-03'

--LO QUE SE VA MOSTRAR EN EL RELOJ CHECADOR 

SELECT 
EMPLEADO.ID_EMPLEADO_TE,
EMPLEADO.NOMBRE,
EMPLEADO.APELLIDO_PATERNO,
EMPLEADO.APELLIDO_MATERNO,
CHECADA.FECHA,
CHECADA.HORA
FROM EMPLEADO
JOIN 
CHECADA 
ON EMPLEADO.ID_EMPLEADO_TE = CHECADA.ID_EMPLEADO_TC
WHERE ID_EMPLEADO_TC = 1 AND FECHA = '2024-11-03';


--REVISAR SI TIENE TODAS LAS CHECADAS 

SELECT * FROM CHECADA 
SELECT * FROM CHECADABONO; 

SELECT COUNT(*) FROM CHECADA WHERE ID_EMPLEADO_TC = 1;

-- TABLA BONO SI CUMPLE CON SUS 4 CHEDADAS SE PONE UNO EN LA TABLA BONO

DELETE FROM CHECADA;
DELETE FROM CHECADA WHERE ID_EMPLEADO_TC = 1

alter table checada add column nvarchar(25);

SELECT * FROM EMPLEADO
SELECT * FROM CHECADA










